version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  microservice1:
    build: ./microservice_1
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"

  microservice2:
    build: ./microservice_2
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    depends_on:
      - rabbitmq